### ISSUE TITLE
Logout resource is missing delete view

### ISSUE THREAD

**Issue by ddeleon267** [learn-co-curriculum/python-p4-authenticating-users#1]
### Canvas Link

https://learning.flatironschool.com/courses/6182/pages/authenticating-users?module_item_id=510936

### Concern

In the logging out section, it looks like the logic just needs to be wrapped in a view/method!

class Logout(Resource):
    session['user_id'] = None
    return jsonify({'message': '204: No Content'}), 204

api.add_resource(Logout, '/logout')

### Suggested Changes

class Logout(Resource):
    def delete(self): # just add this line!
        session['user_id'] = None
        return jsonify({'message': '204: No Content'}), 204

api.add_resource(Logout, '/logout')

**Comment by professor-ben** [comment]
Hi Dominique,

Thanks for reporting this! This should be fixed in GitHub and will be visible on Canvas this evening. (Congrats on being the first contributor on this repo as well!)

-Ben
