### ISSUE TITLE
Possible issue with example code

### ISSUE THREAD

**Issue by SWhalley1130** [learn-co-curriculum/python-p4-authenticating-users#2]
### Canvas Link

https://learning.flatironschool.com/courses/6267/pages/authenticating-users?module_item_id=554261

### Concern

In the code example below, it says to `return jsonify(user.to_dict())`. However, in the [lab following this lesson](https://learning.flatironschool.com/courses/6267/assignments/236239?module_item_id=554262) if you try the same code it has the error 'TypeError: Object of type Response is not JSON serializable'. The lab's [provided solution code](https://github.com/learn-co-curriculum/python-p4-authenticating-users-lab/blob/solution/server/app.py) excludes jsonify. Possibly jsonify should be removed from this example code snippet as well.  

![image](https://user-images.githubusercontent.com/98498031/231568155-5f4d0ed7-39b1-4ef3-a990-d0f16504596f.png)

![image](https://user-images.githubusercontent.com/98498031/231568745-0687868e-1ce9-42bc-b0d8-a0c333c7a7d6.png)

**Comment by professor-ben** [comment]
Hi SWhalley,

Thanks so much for pointing this out. `jsonify` became a bit redundant with the most recent updates to Flask, so we started removing it from lessons and labs. It looks like this one wasn't finished out. I'll push a fix to this later today.

Thanks again,
Ben
